"""
This module defines the FileContainer class. The FileContainer class is used to
represent a file that is inputted to the autodocer. The class contains the name
of the file, the language of the code, and the new file that is generated by the
model.
"""

from core.datatypes import CodeLanguage
from dataclasses import dataclass

@dataclass
class FileContainer:
    path: str
    code_language: CodeLanguage

@dataclass
class CodeDirectoryContainer(FileContainer):
    """Contains the directory of codes."""

@dataclass
class CodeFileContainer(FileContainer):
    """Contains a file of code."""
