"""
This file defines the API of the models module. The models module is
responsible for generating documentation for code. The module contains
the following classes:
    - LLaMa2: The LLaMa2 model. It generates documentation for code using
    the LLaMa2 AI model.
    - ModelResponse: The response from the model. It contains the name of
    the model that generated the response, the language of the code, the
    code that is inputted, the language of the documentation, and the file
    that is generated by the model.

author: @electricalgorithm
"""

from .llama2 import LLaMa2Model
from .base import ModelResponse, ModelBase

__all__ = [
    "LLaMa2Model",
    "ModelResponse",
    "ModelBase"
]
